Numpy library = N-dimensional array 

for mathematical functions 

Homogenous as array in C # actually u can store string in array but u never use it that way 

In [2]:
import numpy as np

In [4]:
a1 = np.array([2,1,4,8])
a1
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
# create a zero matrix of 3by3
a3 = np.zeros((3,3)) 
a3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
a4 = np.ones((2,2))
a4

array([[1., 1.],
       [1., 1.]])

In [19]:
a5 = np.identity(5)
a5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
a6 = np.arange(11)
a6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
equidistant_pts = np.linspace(1,9,3)
equidistant_pts

array([1., 5., 9.])

In [28]:
equidistant_pts = np.linspace(1,50,3)
equidistant_pts

array([ 1. , 25.5, 50. ])

In [30]:
equidistant_pts = np.linspace(1,100,3)
equidistant_pts


array([  1. ,  50.5, 100. ])

In [31]:
# linspace functions takes three arguments, lower_range upper_range and the number to divide the range so that it returns equidistant numbers 

In [40]:
equidistant_pts = np.linspace(1,100,4)
equidistant_pts

# 34-1 = 67-34 = 100-67

array([  1.,  34.,  67., 100.])

In [42]:
a7 = np.array([[[2,3],[4,2]],[[3,9],[1,8]]])
a7

array([[[2, 3],
        [4, 2]],

       [[3, 9],
        [1, 8]]])

In [45]:
a7.shape
# 2 rows and columns of each matrix and such 2 matrices thus 3 dimension 

(2, 2, 2)

In [47]:
a7.ndim

3

IMPORTANT                                                                        

a1 = np.array() and a2 = np.shape #brackets difference why?

in my understanding array() is a function and shape is attribute. a2 is an object of np class, all the attributes of np class is of a2 as well there fore no brackets there

In [51]:
# item and itemsize 
a7.size

8

In [56]:
a7.itemsize # memory took by each element in the array

8

In [58]:
a7.dtype

dtype('int64')

In [59]:
a8 = np.array([[6.7,4.3],[3.2,9.7]])
a8

array([[6.7, 4.3],
       [3.2, 9.7]])

In [60]:
a8.dtype 

dtype('float64')

In [65]:
# want to convert int64 to float64 of a7
new_a7 = a7.astype('float64')
print(new_a7)
print(a7)

[[[2. 3.]
  [4. 2.]]

 [[3. 9.]
  [1. 8.]]]
[[[2 3]
  [4 2]]

 [[3 9]
  [1 8]]]


In [57]:
a7[0,0,0]

2